package com.yanll.business.auth.domain;

import com.yanll.framework.data.mysql.domain.DataEntity;

/*
* 当前文件为MybatisGenerator自动生成，重新生成时会被覆盖，请勿修改！（表结构变化时请重新生成）
* table:m_group_operation_rel
*/
public class GroupOperationRel extends DataEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_group_operation_rel.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_group_operation_rel.group_id
     *
     * @mbg.generated
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_group_operation_rel.operation_id
     *
     * @mbg.generated
     */
    private Long operationId;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_group_operation_rel.id
     *
     * @return the value of m_group_operation_rel.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_group_operation_rel.id
     *
     * @param id the value for m_group_operation_rel.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_group_operation_rel.group_id
     *
     * @return the value of m_group_operation_rel.group_id
     *
     * @mbg.generated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_group_operation_rel.group_id
     *
     * @param groupId the value for m_group_operation_rel.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_group_operation_rel.operation_id
     *
     * @return the value of m_group_operation_rel.operation_id
     *
     * @mbg.generated
     */
    public Long getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_group_operation_rel.operation_id
     *
     * @param operationId the value for m_group_operation_rel.operation_id
     *
     * @mbg.generated
     */
    public void setOperationId(Long operationId) {
        this.operationId = operationId;
    }
}