package com.cmp.common.mappers;

import com.cmp.common.bean.GoodsBrandBean;

public interface GoodsBrandBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_brand
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_brand
     *
     * @mbggenerated
     */
    int insert(GoodsBrandBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_brand
     *
     * @mbggenerated
     */
    int insertSelective(GoodsBrandBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_brand
     *
     * @mbggenerated
     */
    GoodsBrandBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsBrandBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsBrandBean record);
}