package com.cmp.common.mappers;

import com.cmp.common.bean.GoodsImgsBean;

public interface GoodsImgsBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_imgs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_imgs
     *
     * @mbggenerated
     */
    int insert(GoodsImgsBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_imgs
     *
     * @mbggenerated
     */
    int insertSelective(GoodsImgsBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_imgs
     *
     * @mbggenerated
     */
    GoodsImgsBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_imgs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsImgsBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_imgs
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsImgsBean record);
}