package com.cmp.common.mappers;

import com.cmp.common.bean.GoodsTagBean;

public interface GoodsTagBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_tag
     *
     * @mbggenerated
     */
    int insert(GoodsTagBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_tag
     *
     * @mbggenerated
     */
    int insertSelective(GoodsTagBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_tag
     *
     * @mbggenerated
     */
    GoodsTagBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsTagBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsTagBean record);
}