package com.cmp.common.mappers;

import com.cmp.common.bean.IndexDataBean;

public interface IndexDataBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_data
     *
     * @mbggenerated
     */
    int insert(IndexDataBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_data
     *
     * @mbggenerated
     */
    int insertSelective(IndexDataBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_data
     *
     * @mbggenerated
     */
    IndexDataBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IndexDataBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IndexDataBean record);
}