package com.cmp.jp.api.goods.bean;

public class GoodsTypeBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.type_name
     *
     * @mbggenerated
     */
    private String type_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.idx
     *
     * @mbggenerated
     */
    private Long idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.enabled
     *
     * @mbggenerated
     */
    private Integer enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.id
     *
     * @return the value of t_goods_type.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.id
     *
     * @param id the value for t_goods_type.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.type_name
     *
     * @return the value of t_goods_type.type_name
     *
     * @mbggenerated
     */
    public String getType_name() {
        return type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.type_name
     *
     * @param type_name the value for t_goods_type.type_name
     *
     * @mbggenerated
     */
    public void setType_name(String type_name) {
        this.type_name = type_name == null ? null : type_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.img
     *
     * @return the value of t_goods_type.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.img
     *
     * @param img the value for t_goods_type.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.idx
     *
     * @return the value of t_goods_type.idx
     *
     * @mbggenerated
     */
    public Long getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.idx
     *
     * @param idx the value for t_goods_type.idx
     *
     * @mbggenerated
     */
    public void setIdx(Long idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.enabled
     *
     * @return the value of t_goods_type.enabled
     *
     * @mbggenerated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.enabled
     *
     * @param enabled the value for t_goods_type.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
}