package com.cmp.common.bean;

public class GoodsTagBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_tag.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_tag.tag_name
     *
     * @mbggenerated
     */
    private String tag_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_tag.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_tag.idx
     *
     * @mbggenerated
     */
    private Long idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_tag.enabled
     *
     * @mbggenerated
     */
    private Integer enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_tag.id
     *
     * @return the value of t_goods_tag.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_tag.id
     *
     * @param id the value for t_goods_tag.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_tag.tag_name
     *
     * @return the value of t_goods_tag.tag_name
     *
     * @mbggenerated
     */
    public String getTag_name() {
        return tag_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_tag.tag_name
     *
     * @param tag_name the value for t_goods_tag.tag_name
     *
     * @mbggenerated
     */
    public void setTag_name(String tag_name) {
        this.tag_name = tag_name == null ? null : tag_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_tag.img
     *
     * @return the value of t_goods_tag.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_tag.img
     *
     * @param img the value for t_goods_tag.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_tag.idx
     *
     * @return the value of t_goods_tag.idx
     *
     * @mbggenerated
     */
    public Long getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_tag.idx
     *
     * @param idx the value for t_goods_tag.idx
     *
     * @mbggenerated
     */
    public void setIdx(Long idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_tag.enabled
     *
     * @return the value of t_goods_tag.enabled
     *
     * @mbggenerated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_tag.enabled
     *
     * @param enabled the value for t_goods_tag.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
}