package com.cmp.common.bean;

public class GoodsDetailBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.goods_id
     *
     * @mbggenerated
     */
    private Long goods_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.goods_detail
     *
     * @mbggenerated
     */
    private String goods_detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.id
     *
     * @return the value of t_goods_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.id
     *
     * @param id the value for t_goods_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.goods_id
     *
     * @return the value of t_goods_detail.goods_id
     *
     * @mbggenerated
     */
    public Long getGoods_id() {
        return goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.goods_id
     *
     * @param goods_id the value for t_goods_detail.goods_id
     *
     * @mbggenerated
     */
    public void setGoods_id(Long goods_id) {
        this.goods_id = goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.goods_detail
     *
     * @return the value of t_goods_detail.goods_detail
     *
     * @mbggenerated
     */
    public String getGoods_detail() {
        return goods_detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.goods_detail
     *
     * @param goods_detail the value for t_goods_detail.goods_detail
     *
     * @mbggenerated
     */
    public void setGoods_detail(String goods_detail) {
        this.goods_detail = goods_detail == null ? null : goods_detail.trim();
    }
}