package com.cmp.common.bean;

import java.util.Date;

public class IndexDataBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.def_id
     *
     * @mbggenerated
     */
    private Long def_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.sub_title
     *
     * @mbggenerated
     */
    private String sub_title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.img_url
     *
     * @mbggenerated
     */
    private String img_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.enabled
     *
     * @mbggenerated
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.action_type
     *
     * @mbggenerated
     */
    private Integer action_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.action_params
     *
     * @mbggenerated
     */
    private String action_params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.idx
     *
     * @mbggenerated
     */
    private Long idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.add_date
     *
     * @mbggenerated
     */
    private Date add_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.group_uuid
     *
     * @mbggenerated
     */
    private String group_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.wap_url
     *
     * @mbggenerated
     */
    private String wap_url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.id
     *
     * @return the value of t_index_data.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.id
     *
     * @param id the value for t_index_data.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.def_id
     *
     * @return the value of t_index_data.def_id
     *
     * @mbggenerated
     */
    public Long getDef_id() {
        return def_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.def_id
     *
     * @param def_id the value for t_index_data.def_id
     *
     * @mbggenerated
     */
    public void setDef_id(Long def_id) {
        this.def_id = def_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.title
     *
     * @return the value of t_index_data.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.title
     *
     * @param title the value for t_index_data.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.sub_title
     *
     * @return the value of t_index_data.sub_title
     *
     * @mbggenerated
     */
    public String getSub_title() {
        return sub_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.sub_title
     *
     * @param sub_title the value for t_index_data.sub_title
     *
     * @mbggenerated
     */
    public void setSub_title(String sub_title) {
        this.sub_title = sub_title == null ? null : sub_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.description
     *
     * @return the value of t_index_data.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.description
     *
     * @param description the value for t_index_data.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.img_url
     *
     * @return the value of t_index_data.img_url
     *
     * @mbggenerated
     */
    public String getImg_url() {
        return img_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.img_url
     *
     * @param img_url the value for t_index_data.img_url
     *
     * @mbggenerated
     */
    public void setImg_url(String img_url) {
        this.img_url = img_url == null ? null : img_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.enabled
     *
     * @return the value of t_index_data.enabled
     *
     * @mbggenerated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.enabled
     *
     * @param enabled the value for t_index_data.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.action_type
     *
     * @return the value of t_index_data.action_type
     *
     * @mbggenerated
     */
    public Integer getAction_type() {
        return action_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.action_type
     *
     * @param action_type the value for t_index_data.action_type
     *
     * @mbggenerated
     */
    public void setAction_type(Integer action_type) {
        this.action_type = action_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.action_params
     *
     * @return the value of t_index_data.action_params
     *
     * @mbggenerated
     */
    public String getAction_params() {
        return action_params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.action_params
     *
     * @param action_params the value for t_index_data.action_params
     *
     * @mbggenerated
     */
    public void setAction_params(String action_params) {
        this.action_params = action_params == null ? null : action_params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.idx
     *
     * @return the value of t_index_data.idx
     *
     * @mbggenerated
     */
    public Long getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.idx
     *
     * @param idx the value for t_index_data.idx
     *
     * @mbggenerated
     */
    public void setIdx(Long idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.add_date
     *
     * @return the value of t_index_data.add_date
     *
     * @mbggenerated
     */
    public Date getAdd_date() {
        return add_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.add_date
     *
     * @param add_date the value for t_index_data.add_date
     *
     * @mbggenerated
     */
    public void setAdd_date(Date add_date) {
        this.add_date = add_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.group_uuid
     *
     * @return the value of t_index_data.group_uuid
     *
     * @mbggenerated
     */
    public String getGroup_uuid() {
        return group_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.group_uuid
     *
     * @param group_uuid the value for t_index_data.group_uuid
     *
     * @mbggenerated
     */
    public void setGroup_uuid(String group_uuid) {
        this.group_uuid = group_uuid == null ? null : group_uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.wap_url
     *
     * @return the value of t_index_data.wap_url
     *
     * @mbggenerated
     */
    public String getWap_url() {
        return wap_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.wap_url
     *
     * @param wap_url the value for t_index_data.wap_url
     *
     * @mbggenerated
     */
    public void setWap_url(String wap_url) {
        this.wap_url = wap_url == null ? null : wap_url.trim();
    }
}