package com.cmp.common.bean;

public class IndexDataDefBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data_def.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data_def.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data_def.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data_def.icon_url
     *
     * @mbggenerated
     */
    private String icon_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data_def.enabled
     *
     * @mbggenerated
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data_def.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data_def.id
     *
     * @return the value of t_index_data_def.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data_def.id
     *
     * @param id the value for t_index_data_def.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data_def.name
     *
     * @return the value of t_index_data_def.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data_def.name
     *
     * @param name the value for t_index_data_def.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data_def.description
     *
     * @return the value of t_index_data_def.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data_def.description
     *
     * @param description the value for t_index_data_def.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data_def.icon_url
     *
     * @return the value of t_index_data_def.icon_url
     *
     * @mbggenerated
     */
    public String getIcon_url() {
        return icon_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data_def.icon_url
     *
     * @param icon_url the value for t_index_data_def.icon_url
     *
     * @mbggenerated
     */
    public void setIcon_url(String icon_url) {
        this.icon_url = icon_url == null ? null : icon_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data_def.enabled
     *
     * @return the value of t_index_data_def.enabled
     *
     * @mbggenerated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data_def.enabled
     *
     * @param enabled the value for t_index_data_def.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data_def.version
     *
     * @return the value of t_index_data_def.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data_def.version
     *
     * @param version the value for t_index_data_def.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}