package com.yanll.business.indexdata.domain;

import com.yanll.framework.data.mysql.domain.DataEntity;
import java.util.Date;

/*
* 当前文件为MybatisGenerator自动生成，重新生成时会被覆盖，请勿修改！（表结构变化时请重新生成）
* table:t_index_data
*/
public class IndexDataBean extends DataEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.def_id
     *
     * @mbg.generated
     */
    private Long defId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.sub_title
     *
     * @mbg.generated
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.enabled
     *
     * @mbg.generated
     */
    private Integer enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.action_type
     *
     * @mbg.generated
     */
    private Integer actionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.action_params
     *
     * @mbg.generated
     */
    private String actionParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.idx
     *
     * @mbg.generated
     */
    private Long idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.add_date
     *
     * @mbg.generated
     */
    private Date addDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.group_uuid
     *
     * @mbg.generated
     */
    private String groupUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_index_data.wap_url
     *
     * @mbg.generated
     */
    private String wapUrl;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.id
     *
     * @return the value of t_index_data.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.id
     *
     * @param id the value for t_index_data.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.def_id
     *
     * @return the value of t_index_data.def_id
     *
     * @mbg.generated
     */
    public Long getDefId() {
        return defId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.def_id
     *
     * @param defId the value for t_index_data.def_id
     *
     * @mbg.generated
     */
    public void setDefId(Long defId) {
        this.defId = defId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.title
     *
     * @return the value of t_index_data.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.title
     *
     * @param title the value for t_index_data.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.sub_title
     *
     * @return the value of t_index_data.sub_title
     *
     * @mbg.generated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.sub_title
     *
     * @param subTitle the value for t_index_data.sub_title
     *
     * @mbg.generated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.description
     *
     * @return the value of t_index_data.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.description
     *
     * @param description the value for t_index_data.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.img_url
     *
     * @return the value of t_index_data.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.img_url
     *
     * @param imgUrl the value for t_index_data.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.enabled
     *
     * @return the value of t_index_data.enabled
     *
     * @mbg.generated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.enabled
     *
     * @param enabled the value for t_index_data.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.action_type
     *
     * @return the value of t_index_data.action_type
     *
     * @mbg.generated
     */
    public Integer getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.action_type
     *
     * @param actionType the value for t_index_data.action_type
     *
     * @mbg.generated
     */
    public void setActionType(Integer actionType) {
        this.actionType = actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.action_params
     *
     * @return the value of t_index_data.action_params
     *
     * @mbg.generated
     */
    public String getActionParams() {
        return actionParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.action_params
     *
     * @param actionParams the value for t_index_data.action_params
     *
     * @mbg.generated
     */
    public void setActionParams(String actionParams) {
        this.actionParams = actionParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.idx
     *
     * @return the value of t_index_data.idx
     *
     * @mbg.generated
     */
    public Long getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.idx
     *
     * @param idx the value for t_index_data.idx
     *
     * @mbg.generated
     */
    public void setIdx(Long idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.add_date
     *
     * @return the value of t_index_data.add_date
     *
     * @mbg.generated
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.add_date
     *
     * @param addDate the value for t_index_data.add_date
     *
     * @mbg.generated
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.group_uuid
     *
     * @return the value of t_index_data.group_uuid
     *
     * @mbg.generated
     */
    public String getGroupUuid() {
        return groupUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.group_uuid
     *
     * @param groupUuid the value for t_index_data.group_uuid
     *
     * @mbg.generated
     */
    public void setGroupUuid(String groupUuid) {
        this.groupUuid = groupUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_index_data.wap_url
     *
     * @return the value of t_index_data.wap_url
     *
     * @mbg.generated
     */
    public String getWapUrl() {
        return wapUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_index_data.wap_url
     *
     * @param wapUrl the value for t_index_data.wap_url
     *
     * @mbg.generated
     */
    public void setWapUrl(String wapUrl) {
        this.wapUrl = wapUrl;
    }
}