package com.yanll.business.auth.dao;

import com.yanll.business.auth.domain.GroupOperationRel;

public interface GroupOperationRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_group_operation_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_group_operation_rel
     *
     * @mbg.generated
     */
    int insert(GroupOperationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_group_operation_rel
     *
     * @mbg.generated
     */
    int insertSelective(GroupOperationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_group_operation_rel
     *
     * @mbg.generated
     */
    GroupOperationRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_group_operation_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupOperationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_group_operation_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupOperationRel record);
}