package com.yanll.business.auth.dao;

import com.yanll.business.auth.domain.MenuBean;

public interface MenuBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated
     */
    int insert(MenuBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated
     */
    int insertSelective(MenuBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated
     */
    MenuBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MenuBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuBean record);
}