package com.yanll.business.auth.dao;

import com.yanll.business.auth.domain.OperationBean;

public interface OperationBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_operation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_operation
     *
     * @mbg.generated
     */
    int insert(OperationBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_operation
     *
     * @mbg.generated
     */
    int insertSelective(OperationBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_operation
     *
     * @mbg.generated
     */
    OperationBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OperationBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperationBean record);
}