package com.yanll.business.auth.dao;

import com.yanll.business.auth.domain.PermissionGroup;

public interface PermissionGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_permission_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_permission_group
     *
     * @mbg.generated
     */
    int insert(PermissionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_permission_group
     *
     * @mbg.generated
     */
    int insertSelective(PermissionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_permission_group
     *
     * @mbg.generated
     */
    PermissionGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_permission_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PermissionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_permission_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PermissionGroup record);
}