package com.yanll.business.auth.dao;

import com.yanll.business.auth.domain.UserOperationRelBean;

public interface UserOperationRelBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_operation_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_operation_rel
     *
     * @mbg.generated
     */
    int insert(UserOperationRelBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_operation_rel
     *
     * @mbg.generated
     */
    int insertSelective(UserOperationRelBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_operation_rel
     *
     * @mbg.generated
     */
    UserOperationRelBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_operation_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserOperationRelBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_operation_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserOperationRelBean record);
}