package com.yanll.business.auth.dao;

import com.yanll.business.auth.domain.UserGroupRel;

public interface UserGroupRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_group_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_group_rel
     *
     * @mbg.generated
     */
    int insert(UserGroupRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_group_rel
     *
     * @mbg.generated
     */
    int insertSelective(UserGroupRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_group_rel
     *
     * @mbg.generated
     */
    UserGroupRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_group_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserGroupRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_group_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGroupRel record);
}